"""add Department

Revision ID: 92544742f830
Revises: cc43abda1cd8
Create Date: 2024-10-01 17:06:55.521365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92544742f830'
down_revision = 'cc43abda1cd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
